name: 'tuva'
version: '0.1.0'
config-version: 2
profile: 'tuva'   # configuration required


vars:
    source_database: hcup                      # configuration required
    source_schema: public                      # configuration required
    
    source_table_patients: "patients"          # configuration required
    source_table_coverage: "coverage"          # configuration required
    source_table_encounters: "encounters"      # configuration required
    source_table_diagnoses: "diagnoses"        # configuration required
    source_table_procedures: "procedures"      # configuration required

##  Configure each source data table by specifying the schema name and 
##  column name e.g. 
##  table_source: "{{ 'your_schema_name', 'your_table_name' }}"
    patients_source: "{{ source('source_data', var('source_table_patients')) }}"
    coverage_source: "{{ source('source_data', var('source_table_coverage')) }}"
    encounters_source: "{{ source('source_data', var('source_table_encounters')) }}"
    diagnoses_source: "{{ source('source_data', var('source_table_diagnoses')) }}"
    procedures_source: "{{ source('source_data', var('source_table_procedures')) }}"    


source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"  
clean-targets:         
    - "target"
    - "dbt_modules"

models:
  tuva:
    staging:
      +database: tuva
      +schema: staging
    chronic_conditions:
      +database: tuva 
      +schema: chronic_conditions
    ccsr:
      +database: tuva
      +schema: ccsr

seeds:
  tuva:
    +database: tuva
    +schema: seed
