name: 'tuva'
version: '0.1.0'
config-version: 2
profile: 'tuva'                 # configuration required

vars:
    stg_database: desynpuf      # configuration required
    stg_database: staging        # configuration required
    
    stg_patients: "{{ ref('stg_patients') }}"
    stg_coverage: "{{ ref('stg_coverage') }}"
    stg_encounters: "{{ ref('stg_encounters') }}"
    stg_diagnoses: "{{ ref('stg_diagnoses') }}"
    stg_procedures: "{{ ref('stg_procedures') }}"
    stg_medications: "{{ ref('stg_medications') }}"     

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"  
clean-targets:         
    - "target"
    - "dbt_modules"

models:
  tuva:
    +schema: core

seeds:
  tuva:
    +schema: vocabulary
