name: 'tuva'
version: '0.1.2'
config-version: 2
profile: 'syntegra'                  # configuration required

vars:
    source_name: ihm        # configuration required
    source_database: ihm    # configuration required
    source_schema: source       # configuration required

    src_patient: "{{ source(var('source_name'),'stg_patient') }}"
    src_coverage: "{{ source(var('source_name'),'stg_coverage') }}"
    src_encounter: "{{ source(var('source_name'),'stg_encounter') }}"
    src_diagnosis: "{{ source(var('source_name'),'stg_diagnosis') }}"
    src_procedure: "{{ source(var('source_name'),'stg_procedure') }}"

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"  
clean-targets:         
    - "target"
    - "dbt_modules"

models:
  tuva:
    +database: ihm
    +schema: core

seeds:
  tuva:
    +database: ihm
    +schema: vocabulary
    +tags: vocabulary

tests:
  +severity: warn  # all tests
