name: 'tuva'
version: '0.1.0'
config-version: 2
profile: 'tuva'                  # configuration required

vars:
    source_database: desynpuf    # configuration required
    source_schema: staging       # configuration required
    src_patients: "{{ source('source','stg_patients') }}"
    src_coverage: "{{ source('source','stg_coverage') }}"
    src_encounters: "{{ source('source','stg_encounters') }}"
    src_diagnoses: "{{ source('source','stg_diagnoses') }}"
    src_procedures: "{{ source('source','stg_procedures') }}"

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"  
clean-targets:         
    - "target"
    - "dbt_modules"

models:
  tuva:
    +database: tuva
    +schema: core

seeds:
  tuva:
    +database: tuva
    +schema: vocabulary
    +tags: vocabulary
