name: 'tuva'
version: '0.1.0'
config-version: 2
profile: 'tuva'   # configuration required

vars:
    source_database: hcup   # configuration required
    source_schema: public   # configuration required
    target_database: tuva   # configuration optional

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"  
clean-targets:         
    - "target"
    - "dbt_modules"

models:
  tuva:
    staging:
      +database: tuva
      +schema: staging
    chronic_conditions:
      +database: tuva 
      +schema: chronic_conditions

seeds:
  tuva:
    +database: tuva
    +schema: seed
