name: 'integration_tests'
version: '1.0.0'
config-version: 2

profile: 'default'

vars:

  input_database: tuva_project_demo
  input_schema: tuva_synthetic

  ## Input Layer
  input_layer_enabled: true
  
  ## All Data Marts
  tuva_marts_enabled: true

  ## Claims Data Marts
  member_months_enabled: true
  service_category_grouper_enabled: true
  encounter_grouper_enabled: true
  pmpm_enabled: true
  data_profiling_enabled: true
  claims_date_profiling_enabled: true
  #cms_hccs_enabled: false

  ## Core Data Model
  core_enabled: true

  # ## High-level Data Marts
  readmissions_enabled: true
  cms_chronic_conditions_enabled: true
  tuva_chronic_conditions_enabled: true
  ccsr_enabled: true
  ## emergency_department_enabled: false

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  integration_tests:
    +materialized: ephemeral
#  the_tuva_project:
#    +database: tuva_test

# seeds:
#   +database: dev