name: 'integration_tests'
version: '1.0.0'
config-version: 2

profile: tuva-snowflake

vars:

  input_database: medicare_lds_five_percent
  input_schema: tuva_claims

  ## Input Layer
  input_layer_enabled: true
  
  ## All Data Marts
  tuva_marts_enabled: false

  ## Claims Data Marts
  member_months_enabled: false
  service_category_grouper_enabled: true
  encounter_grouper_enabled: false
  pmpm_enabled: false
  data_profiling_enabled: false
  claims_date_profiling_enabled: false
  #cms_hccs_enabled: false

  ## Core Data Model
  core_enabled: false

  # ## High-level Data Marts
  readmissions_enabled: false
  cms_chronic_conditions_enabled: false
  tuva_chronic_conditions_enabled: false
  ccsr_enabled: false
  ## emergency_department_enabled: false

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  integration_tests:
    +materialized: ephemeral
  the_tuva_project:
    +database: medicare_lds_five_percent
    # input_layer:
    #   +schema: input_layer
    # service_category_grouper:
    #   +schema: service_category_grouper

seeds:
  +database: medicare_lds_five_percent
