name: 'integration_tests'
version: '1.0.0'
config-version: 2

profile: tuva-snowflake

vars:

  input_database: medicare_lds_five_percent
  input_schema: input_layer

  ## Input Layer
  input_layer_enabled: true
  
  ## All Data Marts
  tuva_marts_enabled: false

  ## Claims Data Marts
  member_months_enabled: false
  service_category_grouper_enabled: true
  encounter_grouper_enabled: false
  pmpm_enabled: false
  data_profiling_enabled: false
  claims_date_profiling_enabled: false
  #cms_hccs_enabled: false

  ## Core Data Model
  core_enabled: false

  # ## High-level Data Marts
  readmissions_enabled: false
  cms_chronic_conditions_enabled: false
  tuva_chronic_conditions_enabled: false
  ccsr_enabled: false
  ## emergency_department_enabled: false

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  integration_tests:
    +materialized: ephemeral
  the_tuva_project:
   +database: martin_sprocket
   input_layer:
    +schema: input_layer2
   member_months:
    +schema: member_months
   service_category_grouper:
    +schema: service_category_grouper
   encounter_grouper:
    +schema: encounter_grouper
   pmpm:
    +schema: pmpm
   data_profiling:
    +schema: claims_profiling
   claims_date_profiling:
    +schema: claims_profiling
   core:
    +schema: core
   readmissions:
    +schema: readmissions
   chronic_conditions:
    +schema: chronic_conditions
   ccsr:
    +schema: ccsr   

seeds:
  +database: dev_aaron2