version: 2

sources:
  - name: source
    schema: "{{ var('source_schema') }}"
    database: "{{ var('source_database') }}"
    tables:
      - name: patients
        description: "Table containing info about patients (e.g. demographics) with one record per patient."
        columns:
          - name: patient_id
            description: "The primary key for this table (a unique ID for each person)."
          - name: gender_code
            description: "A string that takes one of two values: 'male', 'female' "
          - name: birth_date
            description: "The date of birth of the patient in this format: 'YYYY-mm-dd' "
          - name: deceased_date
            description: "The date of death for each patient. It should only be populated for patients who have died and should be NULL for living patients."
      - name: encounters
        description: "Table containing information about diagnoses (e.g. discharge dates) with one record per encounter."
        columns:
          - name: encounter_id
            description: "The primary key for this table (a unique ID for each encounter)."
          - name: patient_id
            description: "Unique identifier for each patient involved in the encounter."
          - name: encounter_start_date
            description: "The encounter start date in this format: 'YYYY-MM-DD'."
          - name: encounter_end_date
            description: "The encounter end date in this format: 'YYY-MM-DD'."
          - name: admit_type_code
            description: "The admit type code for the encounter.  Indicates type and priority of admission for inpatient hospital stays."
          - name: admit_source_code
            description: "The admit source code for the encounter.  Indicates where the patient came from prior to admission."
          - name: discharge_status_code
            description: "The discharge status code for the encounter.  Indicates where a patient was discharged to."
      - name: diagnoses
        description: "Table containing diagnosis codes with one record per diagnosis code per patient encounter."
        columns:
          - name: encounter_id
            description: "The ID corresponding to the encounter where this diagnosis code occurred."
          - name: diagnosis_code
            description: "ICD-10-CM diagnosis code for this diagnosis."
          - name: diagnosis_code_ranking
            description: "Integer representing the ranking of this diagnosis code.  1 is the primary diagnosis for the encounter.  2 or greater is a secondary diagnosis."
          - name: present_on_admission_code
            description: "Code representing whether the diagnosis was present on admission."
      - name: procedures
        description: "Table containing procedure codes with one record for patient encounter."
        columns:
          - name: encounter_id
            description: "The encounter_id corresponding to the encounter where this performed."
          - name: procedure_code
            description: "ICD-10-PCS procedure code related to this diagnosis."
          - name: procedure_code_ranking
            description: "Integer representing the ranking of this procedure code (e.g. 1,2,3,...)."